// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcmHtyED1KUfNgRT5kLTTB29ylzflZJeo',
    appId: '1:630972371433:web:d49900ff5b3335422cfb78',
    messagingSenderId: '630972371433',
    projectId: 'expense-tracker-b4b61',
    authDomain: 'expense-tracker-b4b61.firebaseapp.com',
    storageBucket: 'expense-tracker-b4b61.firebasestorage.app',
    measurementId: 'G-42R1LRKXHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmp0GUa8MlTZw18x239rwBhv1rS8zS0pE',
    appId: '1:630972371433:android:7d2c1e011fe51cdf2cfb78',
    messagingSenderId: '630972371433',
    projectId: 'expense-tracker-b4b61',
    storageBucket: 'expense-tracker-b4b61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-8qtOXfwpxoW5TToJp35qAEQ3Zj5tz2A',
    appId: '1:630972371433:ios:2b0dfe506b9f99852cfb78',
    messagingSenderId: '630972371433',
    projectId: 'expense-tracker-b4b61',
    storageBucket: 'expense-tracker-b4b61.firebasestorage.app',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-8qtOXfwpxoW5TToJp35qAEQ3Zj5tz2A',
    appId: '1:630972371433:ios:2b0dfe506b9f99852cfb78',
    messagingSenderId: '630972371433',
    projectId: 'expense-tracker-b4b61',
    storageBucket: 'expense-tracker-b4b61.firebasestorage.app',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcmHtyED1KUfNgRT5kLTTB29ylzflZJeo',
    appId: '1:630972371433:web:cf3bf78f19b6ac0f2cfb78',
    messagingSenderId: '630972371433',
    projectId: 'expense-tracker-b4b61',
    authDomain: 'expense-tracker-b4b61.firebaseapp.com',
    storageBucket: 'expense-tracker-b4b61.firebasestorage.app',
    measurementId: 'G-WS9CNEEXE5',
  );
}
